const modules=[
  {n:'01',icon:'⌘',phase:'FOUNDATION',title:'Editor & scene thinking',desc:'Navigate the Editor, compose GameObjects, and save a clean first scene.',output:'Scene ready',time:'45 MIN'},
  {n:'02',icon:'{ }',phase:'FOUNDATION',title:'C# for gameplay',desc:'Use components, fields, methods, references, and the MonoBehaviour lifecycle.',output:'Behavior scripted',time:'75 MIN'},
  {n:'03',icon:'↗',phase:'PLAYABLE LOOP',title:'Input & movement',desc:'Create action-based controls and a physics-driven player controller.',output:'Player moves',time:'60 MIN'},
  {n:'04',icon:'◉',phase:'PLAYABLE LOOP',title:'Physics & interactions',desc:'Build collisions, triggers, collectibles, hazards, and win conditions.',output:'Game loop works',time:'70 MIN'},
  {n:'05',icon:'▦',phase:'RELEASE',title:'UI, audio & polish',desc:'Communicate game state with interfaces, feedback, sound, and particles.',output:'Game feels clear',time:'60 MIN'},
  {n:'06',icon:'△',phase:'RELEASE',title:'Profile, build & ship',desc:'Measure performance, create a Web build, test, and publish your game.',output:'Build is live',time:'50 MIN'}
];
document.querySelector('#moduleGrid').innerHTML=modules.map((m,i)=>`<a href="#module-${m.n}" class="module-card" id="module-${m.n}" data-module-index="${i}" aria-label="Open module ${Number(m.n)}: ${m.title}"><div class="module-top"><span>MODULE ${m.n}</span><span>${m.time}</span></div><span class="module-phase">${m.phase}</span><div class="module-icon" aria-hidden="true">${m.icon}</div><h3>${m.title}</h3><p>${m.desc}</p><span class="module-output">${m.output} <i>→</i></span></a>`).join('');

const challenges=[
 {title:'Find a component',prompt:'Which method caches the Rigidbody already attached to this GameObject?',code:'private Rigidbody body;\n\nvoid Awake()\n{\n    body = ___<Rigidbody>();\n}',choices:['FindComponent','GetComponent','AddComponent','TryGetComponent'],answer:1,explanations:['FindComponent is not a Unity API method.','Correct. GetComponent<T>() returns an existing component of type T on the same GameObject. Caching it in Awake avoids searching for it every physics step.','AddComponent<T>() creates a new component; it does not find the Rigidbody already attached.','TryGetComponent requires an out parameter, so it does not fit this expression.']},
 {title:'Frame-by-frame logic',prompt:'Which lifecycle method should run this visual rotation once per rendered frame?',code:'void ___()\n{\n    transform.Rotate(0f, 60f * Time.deltaTime, 0f);\n}',choices:['Awake','Update','FixedUpdate','OnEnable'],answer:1,explanations:['Awake runs once during initialization, so the object would rotate only once.','Correct. Update runs once per rendered frame. Time.deltaTime converts 60 degrees per second into the correct amount for each frame.','FixedUpdate is meant for physics-timestep work, especially Rigidbody forces. This Transform animation belongs in Update.','OnEnable runs when the component becomes enabled, not every frame.']},
 {title:'Stable physics',prompt:'Which method should apply this Rigidbody force on the physics timestep?',code:'void ___()\n{\n    body.AddForce(Vector3.forward * force);\n}',choices:['Update','LateUpdate','FixedUpdate','Start'],answer:2,explanations:['Update follows rendered frames, whose timing varies. Repeated force application there can make physics inconsistent.','LateUpdate is useful after regular Update work, often for following cameras—not for force application.','Correct. FixedUpdate runs with Unity’s physics timestep, making repeated Rigidbody forces stable and predictable.','Start runs once before the first Update, so it cannot apply continuous force.']},
 {title:'Expose a private field',prompt:'Which attribute makes speed editable in the Inspector while keeping the field private?',code:'[___] private float speed = 5f;',choices:['Header','HideInInspector','SerializeField','RequireComponent'],answer:2,explanations:['Header adds a label above Inspector fields but does not serialize a private field.','HideInInspector does the opposite: it hides a serialized field from the Inspector.','Correct. SerializeField tells Unity to serialize this private field, so designers can tune it without making it public.','RequireComponent ensures another component exists on a GameObject; it does not expose fields.']},
 {title:'Detect a trigger',prompt:'Which callback runs when another 3D Collider first enters this trigger?',code:'private void ___(Collider other)\n{\n    if (other.CompareTag("Player")) Collect();\n}',choices:['OnCollisionEnter','OnTriggerEnter','OnTriggerStay','OnMouseDown'],answer:1,explanations:['OnCollisionEnter handles solid collision contact and receives a Collision parameter, not a Collider parameter.','Correct. OnTriggerEnter(Collider other) runs once when another 3D Collider enters a Collider marked Is Trigger.','OnTriggerStay runs repeatedly while the other Collider remains inside, which could collect or score more than once.','OnMouseDown responds to a pointer click over a Collider, not a physics overlap.']},
 {title:'Create an instance',prompt:'Which Unity method creates a runtime copy of this prefab?',code:'GameObject copy = ___(prefab, spawnPoint.position, Quaternion.identity);',choices:['Destroy','Instantiate','AddComponent','SetActive'],answer:1,explanations:['Destroy removes an Object at the end of the frame.','Correct. Instantiate clones the prefab and can set the new copy’s position and rotation in the same call.','AddComponent adds one component to an existing GameObject; it does not clone a prefab.','SetActive only enables or disables an existing GameObject.']},
 {title:'Wait in a coroutine',prompt:'Which yield instruction pauses this coroutine for about two scaled seconds?',code:'yield return new ___(2f);',choices:['WaitForSeconds','Time.deltaTime','Invoke','Task.Delay'],answer:0,explanations:['Correct. WaitForSeconds yields the coroutine and resumes it after the requested scaled game time.','Time.deltaTime is a float containing the last frame duration; it is not a yield instruction.','Invoke schedules a named MonoBehaviour method and does not fit after “yield return new”.','Task.Delay belongs to async task workflows and is not the Unity coroutine yield object shown here.']},
 {title:'Load a scene',prompt:'Which SceneManager method loads the scene named Level02?',code:'using UnityEngine.SceneManagement;\n\nSceneManager.___("Level02");',choices:['OpenScene','LoadScene','SetActiveScene','MoveGameObjectToScene'],answer:1,explanations:['OpenScene is an Editor workflow API, not the runtime SceneManager call shown here.','Correct. SceneManager.LoadScene loads a scene by name or build index; the scene must be included in the build configuration.','SetActiveScene chooses the active scene among scenes already loaded; it does not load Level02.','MoveGameObjectToScene transfers an existing GameObject between loaded scenes.']}
];
const challengeConcepts={
 'Find a component':['A script can ask its own GameObject for an attached component, then keep that reference for later work.',['GameObject','GetComponent<T>()','Cached field']],
 'Frame-by-frame logic':['Use Update for visual or input-driven work that must react once per rendered frame. Scale continuous change by deltaTime.',['Rendered frame','Update()','deltaTime-scaled change']],
 'Stable physics':['Unity advances physics on a fixed timestep. Repeated Rigidbody forces belong in that rhythm.',['Physics tick','FixedUpdate()','AddForce()']],
 'Expose a private field':['SerializeField keeps code ownership private while letting a designer tune the value in the Inspector.',['Private field','[SerializeField]','Inspector control']],
 'Detect a trigger':['A trigger reports overlap events without creating a solid collision response. Use the enter event for one-time actions.',['Collider enters','OnTriggerEnter','Collect once']],
 'Create an instance':['A Prefab is the stored recipe; Instantiate creates a live runtime copy at a chosen position and rotation.',['Prefab asset','Instantiate()','Scene instance']],
 'Wait in a coroutine':['A coroutine can yield a wait instruction and resume later without blocking Unity’s main loop.',['Coroutine starts','WaitForSeconds','Resume later']],
 'Load a scene':['Runtime scene loading uses SceneManager and a scene that is included in the active build configuration.',['Build scene list','LoadScene()','New scene active']]
};
let challengeIndex=0;const completedChallenges=new Set();
const list=document.querySelector('#challengeList');
function renderChallengeList(){list.innerHTML=challenges.map((c,i)=>`<button class="challenge-tab ${i===challengeIndex?'active':''} ${completedChallenges.has(i)?'complete':''}" data-i="${i}"><span>${completedChallenges.has(i)?'✓':String(i+1).padStart(2,'0')}</span><b>${c.title}</b></button>`).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>{challengeIndex=+b.dataset.i;renderChallenge()})}
function renderChallenge(){const c=challenges[challengeIndex],concept=challengeConcepts[c.title];document.querySelector('#challengeLabel').textContent=`QUESTION ${String(challengeIndex+1).padStart(2,'0')} / 08`;document.querySelector('#challengeTitle').textContent=c.title;document.querySelector('#challengeConcept').innerHTML=`<span class="primer-label">LEARN THIS FIRST</span><p>${concept[0]}</p><div class="mini-flow" aria-label="${concept[1].join(' then ')}">${concept[1].map(step=>`<span>${step}</span>`).join('')}</div>`;document.querySelector('#challengePrompt').textContent=c.prompt;document.querySelector('#challengeCode').innerHTML=c.code.replace('___','<span class="blank-token">___</span>');document.querySelector('#codeFeedback').innerHTML='';document.querySelector('#codeFeedback').className='feedback code-explanation';const options=document.querySelector('#codeMcqOptions');options.innerHTML=c.choices.map((choice,i)=>`<button class="code-mcq-option" type="button" data-choice="${i}"><span>${String.fromCharCode(65+i)}</span><code>${choice}</code></button>`).join('');options.querySelectorAll('button').forEach(button=>button.onclick=()=>checkChallengeAnswer(Number(button.dataset.choice)));renderChallengeList()}
function checkChallengeAnswer(selected){const c=challenges[challengeIndex];const correct=selected===c.answer;const buttons=document.querySelectorAll('#codeMcqOptions button');buttons.forEach((button,i)=>{button.classList.toggle('wrong',i===selected&&!correct);button.classList.toggle('correct',i===c.answer&&correct)});const fb=document.querySelector('#codeFeedback');fb.innerHTML=`<strong>${correct?'Correct — well done.':'Not quite — try again.'}</strong><p>${c.explanations[selected]}</p>`;fb.className=`feedback code-explanation show ${correct?'good':'bad'}`;if(correct){buttons.forEach(button=>button.disabled=true);document.querySelector('#challengeCode').innerHTML=c.code.replace('___',`<span class="solved-token">${c.choices[c.answer]}</span>`);completedChallenges.add(challengeIndex);localStorage.setItem('unityChallenges',JSON.stringify([...completedChallenges]));renderChallengeList()}}
document.querySelector('#nextChallenge').onclick=()=>{challengeIndex=(challengeIndex+1)%challenges.length;renderChallenge()};
try{JSON.parse(localStorage.getItem('unityChallenges')||'[]').forEach(i=>completedChallenges.add(i))}catch{}renderChallenge();

const quiz=[
 ['Editor','What is the fundamental container for components in a Unity scene?',['Asset','GameObject','Package','Assembly'],1,'A GameObject is the scene-level container; components give it data and behavior.'],
 ['Editor','Which component does every GameObject always have?',['Transform','Collider','Rigidbody','Renderer'],0,'Every GameObject has a Transform for position, rotation, scale, and hierarchy.'],
 ['Editor','Where do you edit the properties of a selected component?',['Project window','Console','Inspector','Profiler'],2,'The Inspector displays and edits the selected object and its components.'],
 ['Editor','What is a Prefab primarily used for?',['Reusable object configuration','Writing shaders','Installing Unity','Recording audio'],0,'A Prefab stores a reusable configured GameObject hierarchy as an asset.'],
 ['C#','Which base class is commonly used for scripts attached to GameObjects?',['ScriptableObject','MonoBehaviour','System.Object','EditorWindow'],1,'MonoBehaviour scripts are components and receive Unity lifecycle messages.'],
 ['C#','When is Awake commonly used?',['Every physics step','Initial reference setup','After quitting','Only in Web builds'],1,'Awake is suited to internal initialization and caching references.'],
 ['C#','What does [SerializeField] do on a private field?',['Makes it static','Shows it in the Inspector','Makes it read-only','Deletes it at runtime'],1,'SerializeField asks Unity to serialize the field, making it editable in the Inspector.'],
 ['C#','Why multiply frame-based movement by Time.deltaTime?',['Add gravity','Make it frame-rate independent','Enable collisions','Increase resolution'],1,'deltaTime scales change by elapsed frame time, reducing frame-rate dependence.'],
 ['Input','What is the main advantage of Input Actions?',['They only support keyboards','They decouple intent from devices','They remove C#','They require no configuration'],1,'Actions describe intent such as Move or Jump and can bind to multiple devices.'],
 ['Input','Which value type usually represents a 2D move action?',['bool','Vector2','Quaternion','Color'],1,'A Vector2 holds horizontal and vertical action values.'],
 ['Input','Where should you normally read responsive player input?',['OnDestroy','Update or action callbacks','OnValidate only','A constructor'],1,'Update or Input System callbacks capture player intent responsively.'],
 ['Input','For 3D ground movement, Vector2 input is commonly mapped to which axes?',['X and Z','X and Y rotation','Y and Z scale','W and X'],0,'Unity uses Y as up, so ground-plane movement commonly uses X and Z.'],
 ['Physics','Which component lets a 3D object participate in force-based physics?',['AudioSource','Rigidbody','Canvas','Animator'],1,'Rigidbody gives an object velocity, mass, gravity, and force-based simulation.'],
 ['Physics','Where should Rigidbody forces usually be applied?',['FixedUpdate','OnGUI','Reset','LateUpdate only'],0,'FixedUpdate follows the physics timestep and is the standard place for force application.'],
 ['Physics','What must a trigger Collider have enabled?',['Is Trigger','Static','Convex always','Read/Write'],0,'The Is Trigger setting makes overlaps generate trigger callbacks instead of solid contacts.'],
 ['Physics','Which comparison avoids string-heavy manual tag checks?',['name ==','CompareTag','GetType','ReferenceEquals'],1,'CompareTag is Unity’s intended way to check a GameObject tag.'],
 ['Gameplay','Which API creates a runtime copy of a prefab?',['Instantiate','Serialize','Normalize','Broadcast'],0,'Object.Instantiate clones an object or prefab at runtime.'],
 ['Gameplay','Which construct spreads work across multiple frames?',['Coroutine','Property','Namespace','Enum'],0,'A coroutine can yield and continue later without blocking the main thread.'],
 ['UI & Audio','Which component plays an AudioClip in a scene?',['AudioListener','AudioSource','MixerGroup','Speaker'],1,'An AudioSource is attached to a GameObject to play AudioClips.'],
 ['UI & Audio','A world-space health bar should usually live on which component?',['Canvas','Rigidbody','Terrain','NavMesh'],0,'A Canvas in World Space can position UI within the 3D scene.'],
 ['Publishing','Where are scenes selected for a Unity 6 build?',['Build Profiles','Console settings','Package Manager','Animator'],0,'Unity 6 uses Build Profiles to configure platforms and included scenes.'],
 ['Publishing','Which target publishes a Unity game for modern web browsers?',['Web','Dedicated Server only','tvOS','VisionOS'],0,'The Web platform produces a browser-deliverable build.'],
 ['Performance','What should you do before optimizing?',['Guess the bottleneck','Measure with the Profiler','Remove all textures','Rewrite everything'],1,'Profiling identifies where time and memory are actually spent.'],
 ['Performance','Where should final performance be measured when possible?',['Only in the Editor','On the target platform','In the Inspector','In edit mode'],1,'Target-platform profiling reflects the real device and build environment.']
];
const quizStudyNotes={
 'Editor':['Scene objects are built by attaching focused components to GameObjects. The Inspector edits the selected object; Prefabs preserve reusable configurations.',['GameObject','Components','Reusable Prefab']],
 'C#':['A MonoBehaviour becomes a component. Awake prepares references, serialized fields expose tuning, and Update handles frame-based behavior.',['Awake setup','Update behavior','Inspector tuning']],
 'Input':['Input Actions describe player intent independently from a keyboard, gamepad, or other device. A 2D Move action usually becomes X/Z movement.',['Device binding','Input Action','Gameplay intent']],
 'Physics':['A Rigidbody owns force-based motion. Colliders describe contact shapes, while triggers report overlaps without blocking.',['Collider / trigger','Rigidbody simulation','Interaction event']],
 'Gameplay':['A gameplay loop reacts to events, changes state, and gives feedback. Prefab instances and coroutines help create and time those changes.',['Player event','State changes','Feedback / result']],
 'UI & Audio':['UI and audio translate hidden game state into feedback the player can immediately see or hear.',['Game state','Canvas / AudioSource','Player feedback']],
 'Publishing':['A Build Profile chooses the target platform and included scenes. A Web build packages the game for modern browsers.',['Build Profile','Included scenes','Web release']],
 'Performance':['Optimization starts with evidence. Profile representative gameplay on the target platform, find the bottleneck, then change one cause.',['Measure','Find bottleneck','Optimize & verify']]
};
let quizIndex=0,selected=null,checked=false,score=0,quizMode=localStorage.getItem('unityQuizMode')==='practice'?'practice':'study';
const q=id=>document.querySelector(id);
function syncQuizMode(){const study=quizMode==='study';q('#quizStudyMode').classList.toggle('active',study);q('#quizStudyMode').setAttribute('aria-pressed',String(study));q('#quizPracticeMode').classList.toggle('active',!study);q('#quizPracticeMode').setAttribute('aria-pressed',String(!study));q('#quizCard').classList.toggle('questions-only',!study)}
function renderQuiz(){const item=quiz[quizIndex],note=quizStudyNotes[item[0]];q('#quizCounter').textContent=`QUESTION ${String(quizIndex+1).padStart(2,'0')} / ${quiz.length}`;q('#quizScore').textContent=`${score} XP`;q('#quizProgress').style.width=`${((quizIndex+1)/quiz.length)*100}%`;q('#quizTopic').textContent=item[0].toUpperCase();q('#quizPrimer').innerHTML=`<span class="primer-label">CONCEPT BEFORE QUESTION</span><h4>${item[0]} mental model</h4><p>${note[0]}</p><div class="mini-flow" aria-label="${note[1].join(' then ')}">${note[1].map(step=>`<span>${step}</span>`).join('')}</div>`;q('#quizQuestion').textContent=item[1];q('#quizAnswers').innerHTML=item[2].map((a,i)=>`<button class="answer" data-i="${i}"><b>${String.fromCharCode(65+i)}.</b> ${a}</button>`).join('');q('#quizExplanation').className='quiz-explanation';q('#quizExplanation').textContent='';q('#quizNext').textContent='Check answer';q('#quizNext').disabled=true;selected=null;checked=false;syncQuizMode();q('#quizAnswers').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(checked)return;selected=+b.dataset.i;q('#quizAnswers').querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));q('#quizNext').disabled=false})}
q('#quizStudyMode').onclick=()=>{quizMode='study';localStorage.setItem('unityQuizMode',quizMode);syncQuizMode()};
q('#quizPracticeMode').onclick=()=>{quizMode='practice';localStorage.setItem('unityQuizMode',quizMode);syncQuizMode()};
q('#quizNext').onclick=()=>{if(!checked){checked=true;const item=quiz[quizIndex];const buttons=q('#quizAnswers').querySelectorAll('button');buttons.forEach((b,i)=>{b.disabled=true;if(i===item[3])b.classList.add('correct');if(i===selected&&i!==item[3])b.classList.add('wrong')});if(selected===item[3])score+=50;q('#quizScore').textContent=`${score} XP`;q('#quizExplanation').innerHTML=`<b>${selected===item[3]?'Correct.':'Review this:'}</b> ${item[4]}`;q('#quizExplanation').className='quiz-explanation show';q('#quizNext').textContent=quizIndex===quiz.length-1?'See results':'Next question →'}else if(quizIndex<quiz.length-1){quizIndex++;renderQuiz()}else{const pct=Math.round(score/(quiz.length*50)*100);q('#quizCard').innerHTML=`<div class="quiz-status"><span>ASSESSMENT COMPLETE</span><span>${score} XP</span></div><div class="quiz-progress"><span style="width:${pct}%"></span></div><p class="quiz-topic">YOUR RESULT</p><h3>${pct}% — ${pct>=85?'Ready to build.':pct>=65?'Strong foundation.':'Keep experimenting.'}</h3><p>${pct>=85?'Start your prototype and return to the code lab when you get stuck.':pct>=65?'Review the explanations you missed, then build a small scene.':'Work through the six modules and retake this check after your first prototype.'}</p><button class="button primary" id="restartQuiz">Try again</button>`;q('#restartQuiz').onclick=()=>location.reload()}};renderQuiz();

const form=q('#planForm');const result=q('#planResult');const saved=localStorage.getItem('unityPlan');if(saved){try{const d=JSON.parse(saved);Object.entries(d).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v})}catch{}}
const target=new Date();target.setDate(target.getDate()+42);q('#shipDate').value=q('#shipDate').value||target.toISOString().slice(0,10);
form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));localStorage.setItem('unityPlan',JSON.stringify(data));const sessions=Math.max(2,Math.ceil(+data.hours/2));result.innerHTML=`<b>Plan saved, ${data.studentName}.</b> Schedule ${sessions} focused sessions each week. Your first milestone is a controllable prototype of “${data.gameIdea}”; your ship date is ${new Date(data.shipDate+'T00:00:00').toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}.`;result.classList.add('show')};

const themeButton=q('#themeToggle');function syncThemeButton(){const dark=document.body.classList.contains('dark');themeButton.setAttribute('aria-pressed',String(dark));themeButton.setAttribute('title',dark?'Switch to light mode':'Switch to dark mode')}themeButton.onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('unityTheme',document.body.classList.contains('dark')?'dark':'light');syncThemeButton()};if(localStorage.getItem('unityTheme')==='dark')document.body.classList.add('dark');syncThemeButton();
const copyCodeButton=document.querySelector('.copy-code');if(copyCodeButton)copyCodeButton.onclick=async e=>{const text=e.currentTarget.closest('.code-window').querySelector('code').innerText;await navigator.clipboard.writeText(text);e.currentTarget.textContent='Copied ✓';setTimeout(()=>e.currentTarget.textContent='Copy code',1500)};
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
