const modules=[
  {n:'01',icon:'⌘',title:'Editor & scene thinking',desc:'Navigate the Editor, compose GameObjects, and save a clean first scene.',time:'45 MIN'},
  {n:'02',icon:'{ }',title:'C# for gameplay',desc:'Use components, fields, methods, references, and the MonoBehaviour lifecycle.',time:'75 MIN'},
  {n:'03',icon:'↗',title:'Input & movement',desc:'Create action-based controls and a physics-driven player controller.',time:'60 MIN'},
  {n:'04',icon:'◉',title:'Physics & interactions',desc:'Build collisions, triggers, collectibles, hazards, and win conditions.',time:'70 MIN'},
  {n:'05',icon:'▦',title:'UI, audio & polish',desc:'Communicate game state with interfaces, feedback, sound, and particles.',time:'60 MIN'},
  {n:'06',icon:'△',title:'Profile, build & ship',desc:'Measure performance, create a Web build, test, and publish your game.',time:'50 MIN'}
];
document.querySelector('#moduleGrid').innerHTML=modules.map(m=>`<article class="module-card reveal"><div class="module-top"><span>MODULE ${m.n}</span><span>${m.time}</span></div><div class="module-icon">${m.icon}</div><h3>${m.title}</h3><p>${m.desc}</p></article>`).join('');

const challenges=[
 {title:'Find a component',prompt:'Cache the Rigidbody attached to this GameObject.',code:'private Rigidbody body;\n\nvoid Awake()\n{\n    body = ___<Rigidbody>();\n}',answer:'GetComponent',hint:'This generic MonoBehaviour method starts with “Get”.'},
 {title:'Frame-by-frame logic',prompt:'Choose the lifecycle method called once per rendered frame.',code:'void ___()\n{\n    transform.Rotate(0f, 60f * Time.deltaTime, 0f);\n}',answer:'Update',hint:'Use this for visual movement and reading input.'},
 {title:'Stable physics',prompt:'Choose the lifecycle method intended for physics work.',code:'void ___()\n{\n    body.AddForce(Vector3.forward * force);\n}',answer:'FixedUpdate',hint:'Its timestep is fixed rather than tied to rendered frames.'},
 {title:'Expose a private field',prompt:'Make speed editable in the Inspector while keeping it private.',code:'[___] private float speed = 5f;',answer:'SerializeField',hint:'It is an attribute placed inside square brackets.'},
 {title:'Detect a trigger',prompt:'Complete the 3D trigger callback method name.',code:'private void ___(Collider other)\n{\n    if (other.CompareTag("Player")) Collect();\n}',answer:'OnTriggerEnter',hint:'It begins with “On” and runs when another Collider enters.'},
 {title:'Create an instance',prompt:'Spawn the prefab at a position and rotation.',code:'GameObject copy = ___(prefab, spawnPoint.position, Quaternion.identity);',answer:'Instantiate',hint:'This Unity method creates a copy of an Object.'},
 {title:'Wait in a coroutine',prompt:'Pause the coroutine for two seconds.',code:'yield return new ___(2f);',answer:'WaitForSeconds',hint:'The type name describes exactly what it does.'},
 {title:'Load a scene',prompt:'Complete the API call that opens a scene by name.',code:'using UnityEngine.SceneManagement;\n\nSceneManager.___("Level02");',answer:'LoadScene',hint:'It is a SceneManager method beginning with “Load”.'}
];
let challengeIndex=0;const completedChallenges=new Set();
const list=document.querySelector('#challengeList');
function renderChallengeList(){list.innerHTML=challenges.map((c,i)=>`<button class="challenge-tab ${i===challengeIndex?'active':''} ${completedChallenges.has(i)?'complete':''}" data-i="${i}"><span>${completedChallenges.has(i)?'✓':String(i+1).padStart(2,'0')}</span><b>${c.title}</b></button>`).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>{challengeIndex=+b.dataset.i;renderChallenge()})}
function renderChallenge(){const c=challenges[challengeIndex];document.querySelector('#challengeLabel').textContent=`CHALLENGE ${String(challengeIndex+1).padStart(2,'0')} / 08`;document.querySelector('#challengeTitle').textContent=c.title;document.querySelector('#challengePrompt').textContent=c.prompt;document.querySelector('#challengeCode').innerHTML=c.code.replace('___','<span class="blank-token">___</span>');document.querySelector('#codeAnswer').value='';document.querySelector('#codeFeedback').textContent='';document.querySelector('#codeFeedback').className='feedback';renderChallengeList()}
document.querySelector('#checkCode').onclick=()=>{const value=document.querySelector('#codeAnswer').value.trim().replace(/\(\)$/,'');const correct=value.toLowerCase()===challenges[challengeIndex].answer.toLowerCase();const fb=document.querySelector('#codeFeedback');fb.textContent=correct?'Correct — that code compiles in this context.':'Not quite. Check capitalization and enter only the missing token.';fb.className=`feedback ${correct?'good':'bad'}`;if(correct){completedChallenges.add(challengeIndex);localStorage.setItem('unityChallenges',JSON.stringify([...completedChallenges]));renderChallengeList()}};
document.querySelector('#showHint').onclick=()=>{const fb=document.querySelector('#codeFeedback');fb.textContent=`Hint: ${challenges[challengeIndex].hint}`;fb.className='feedback'};
document.querySelector('#nextChallenge').onclick=()=>{challengeIndex=(challengeIndex+1)%challenges.length;renderChallenge()};
try{JSON.parse(localStorage.getItem('unityChallenges')||'[]').forEach(i=>completedChallenges.add(i))}catch{}renderChallenge();

const quiz=[
 ['Editor','What is the fundamental container for components in a Unity scene?',['Asset','GameObject','Package','Assembly'],1,'A GameObject is the scene-level container; components give it data and behavior.'],
 ['Editor','Which component does every GameObject always have?',['Transform','Collider','Rigidbody','Renderer'],0,'Every GameObject has a Transform for position, rotation, scale, and hierarchy.'],
 ['Editor','Where do you edit the properties of a selected component?',['Project window','Console','Inspector','Profiler'],2,'The Inspector displays and edits the selected object and its components.'],
 ['Editor','What is a Prefab primarily used for?',['Reusable object configuration','Writing shaders','Installing Unity','Recording audio'],0,'A Prefab stores a reusable configured GameObject hierarchy as an asset.'],
 ['C#','Which base class is commonly used for scripts attached to GameObjects?',['ScriptableObject','MonoBehaviour','System.Object','EditorWindow'],1,'MonoBehaviour scripts are components and receive Unity lifecycle messages.'],
 ['C#','When is Awake commonly used?',['Every physics step','Initial reference setup','After quitting','Only in Web builds'],1,'Awake is suited to internal initialization and caching references.'],
 ['C#','What does [SerializeField] do on a private field?',['Makes it static','Shows it in the Inspector','Makes it read-only','Deletes it at runtime'],1,'SerializeField asks Unity to serialize the field, making it editable in the Inspector.'],
 ['C#','Why multiply frame-based movement by Time.deltaTime?',['Add gravity','Make it frame-rate independent','Enable collisions','Increase resolution'],1,'deltaTime scales change by elapsed frame time, reducing frame-rate dependence.'],
 ['Input','What is the main advantage of Input Actions?',['They only support keyboards','They decouple intent from devices','They remove C#','They require no configuration'],1,'Actions describe intent such as Move or Jump and can bind to multiple devices.'],
 ['Input','Which value type usually represents a 2D move action?',['bool','Vector2','Quaternion','Color'],1,'A Vector2 holds horizontal and vertical action values.'],
 ['Input','Where should you normally read responsive player input?',['OnDestroy','Update or action callbacks','OnValidate only','A constructor'],1,'Update or Input System callbacks capture player intent responsively.'],
 ['Input','For 3D ground movement, Vector2 input is commonly mapped to which axes?',['X and Z','X and Y rotation','Y and Z scale','W and X'],0,'Unity uses Y as up, so ground-plane movement commonly uses X and Z.'],
 ['Physics','Which component lets a 3D object participate in force-based physics?',['AudioSource','Rigidbody','Canvas','Animator'],1,'Rigidbody gives an object velocity, mass, gravity, and force-based simulation.'],
 ['Physics','Where should Rigidbody forces usually be applied?',['FixedUpdate','OnGUI','Reset','LateUpdate only'],0,'FixedUpdate follows the physics timestep and is the standard place for force application.'],
 ['Physics','What must a trigger Collider have enabled?',['Is Trigger','Static','Convex always','Read/Write'],0,'The Is Trigger setting makes overlaps generate trigger callbacks instead of solid contacts.'],
 ['Physics','Which comparison avoids string-heavy manual tag checks?',['name ==','CompareTag','GetType','ReferenceEquals'],1,'CompareTag is Unity’s intended way to check a GameObject tag.'],
 ['Gameplay','Which API creates a runtime copy of a prefab?',['Instantiate','Serialize','Normalize','Broadcast'],0,'Object.Instantiate clones an object or prefab at runtime.'],
 ['Gameplay','Which construct spreads work across multiple frames?',['Coroutine','Property','Namespace','Enum'],0,'A coroutine can yield and continue later without blocking the main thread.'],
 ['UI & Audio','Which component plays an AudioClip in a scene?',['AudioListener','AudioSource','MixerGroup','Speaker'],1,'An AudioSource is attached to a GameObject to play AudioClips.'],
 ['UI & Audio','A world-space health bar should usually live on which component?',['Canvas','Rigidbody','Terrain','NavMesh'],0,'A Canvas in World Space can position UI within the 3D scene.'],
 ['Publishing','Where are scenes selected for a Unity 6 build?',['Build Profiles','Console settings','Package Manager','Animator'],0,'Unity 6 uses Build Profiles to configure platforms and included scenes.'],
 ['Publishing','Which target publishes a Unity game for modern web browsers?',['Web','Dedicated Server only','tvOS','VisionOS'],0,'The Web platform produces a browser-deliverable build.'],
 ['Performance','What should you do before optimizing?',['Guess the bottleneck','Measure with the Profiler','Remove all textures','Rewrite everything'],1,'Profiling identifies where time and memory are actually spent.'],
 ['Performance','Where should final performance be measured when possible?',['Only in the Editor','On the target platform','In the Inspector','In edit mode'],1,'Target-platform profiling reflects the real device and build environment.']
];
let quizIndex=0,selected=null,checked=false,score=0;
const q=id=>document.querySelector(id);
function renderQuiz(){const item=quiz[quizIndex];q('#quizCounter').textContent=`QUESTION ${String(quizIndex+1).padStart(2,'0')} / ${quiz.length}`;q('#quizScore').textContent=`${score} XP`;q('#quizProgress').style.width=`${((quizIndex+1)/quiz.length)*100}%`;q('#quizTopic').textContent=item[0].toUpperCase();q('#quizQuestion').textContent=item[1];q('#quizAnswers').innerHTML=item[2].map((a,i)=>`<button class="answer" data-i="${i}"><b>${String.fromCharCode(65+i)}.</b> ${a}</button>`).join('');q('#quizExplanation').className='quiz-explanation';q('#quizExplanation').textContent='';q('#quizNext').textContent='Check answer';q('#quizNext').disabled=true;selected=null;checked=false;q('#quizAnswers').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(checked)return;selected=+b.dataset.i;q('#quizAnswers').querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));q('#quizNext').disabled=false})}
q('#quizNext').onclick=()=>{if(!checked){checked=true;const item=quiz[quizIndex];const buttons=q('#quizAnswers').querySelectorAll('button');buttons.forEach((b,i)=>{b.disabled=true;if(i===item[3])b.classList.add('correct');if(i===selected&&i!==item[3])b.classList.add('wrong')});if(selected===item[3])score+=50;q('#quizScore').textContent=`${score} XP`;q('#quizExplanation').innerHTML=`<b>${selected===item[3]?'Correct.':'Review this:'}</b> ${item[4]}`;q('#quizExplanation').className='quiz-explanation show';q('#quizNext').textContent=quizIndex===quiz.length-1?'See results':'Next question →'}else if(quizIndex<quiz.length-1){quizIndex++;renderQuiz()}else{const pct=Math.round(score/(quiz.length*50)*100);q('#quizCard').innerHTML=`<div class="quiz-status"><span>ASSESSMENT COMPLETE</span><span>${score} XP</span></div><div class="quiz-progress"><span style="width:${pct}%"></span></div><p class="quiz-topic">YOUR RESULT</p><h3>${pct}% — ${pct>=85?'Ready to build.':pct>=65?'Strong foundation.':'Keep experimenting.'}</h3><p>${pct>=85?'Start your prototype and return to the code lab when you get stuck.':pct>=65?'Review the explanations you missed, then build a small scene.':'Work through the six modules and retake this check after your first prototype.'}</p><button class="button primary" id="restartQuiz">Try again</button>`;q('#restartQuiz').onclick=()=>location.reload()}};renderQuiz();

const form=q('#planForm');const result=q('#planResult');const saved=localStorage.getItem('unityPlan');if(saved){try{const d=JSON.parse(saved);Object.entries(d).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v})}catch{}}
const target=new Date();target.setDate(target.getDate()+42);q('#shipDate').value=q('#shipDate').value||target.toISOString().slice(0,10);
form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));localStorage.setItem('unityPlan',JSON.stringify(data));const sessions=Math.max(2,Math.ceil(+data.hours/2));result.innerHTML=`<b>Plan saved, ${data.studentName}.</b> Schedule ${sessions} focused sessions each week. Your first milestone is a controllable prototype of “${data.gameIdea}”; your ship date is ${new Date(data.shipDate+'T00:00:00').toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}.`;result.classList.add('show')};

q('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('unityTheme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('unityTheme')==='dark')document.body.classList.add('dark');
document.querySelector('.copy-code').onclick=async e=>{const text=e.currentTarget.closest('.code-window').querySelector('code').innerText;await navigator.clipboard.writeText(text);e.currentTarget.textContent='Copied ✓';setTimeout(()=>e.currentTarget.textContent='Copy code',1500)};
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
